### ISSUE TITLE
Assess Two low security vulnerabilities 

### ISSUE THREAD

**Issue by Jarrettledbetter** [ItsIsaiaah/CSS-Final-Project#9]

**Comment by ItsIsaiaah** [comment]
I ran a vulnerability assessment of the DVWA with a low-security level. One of the alerts I got was a medium-level risk that was in regard to the Content Security Policy (CSP) Header not being set. The CSP is an added layer of security that helps to detect and mitigate certain types of attacks. The need for the CSP provides a set of standards for HTTP headers that allow website owners to declare approved sources of content that browsers should be allowed to load on that page. A possible remedy for this is to ensure that the web server, application server, and load balancer are configured to set the Content-Security-Policy header. The other alert we received is a Cookie No HttpOnly Flag with a low risk. This alert is just that a cookie has been set without the HttpOnly flag, which means that the cookie can be accessed by JavaScript which leaves the website vulnerable to malicious scripts. If the malicious script were to be run, then the cookie would be accessible and can be transmitted to another site, ultimately Session Hijacking is possible if the transmitted cookie is a session cookie.
